#!/bin/bash
set -euo pipefail

# Auto-packaging script for AnyKernel3 flashable ZIPs
# Supports: dipper, polaris, beryllium, equuleus, perseus, ursa

KERNEL_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$KERNEL_DIR"

# Config
BRANCH_SHORT="resukisu-susfs"
KERNEL_BASE="dipper-q-oss"
DEVICES=("dipper" "polaris" "beryllium" "equuleus" "perseus" "ursa")
DEFCONFIGS=("dipper_user_defconfig" "polaris_user_defconfig" "beryllium_user_defconfig" "equuleus_user_defconfig" "perseus_user_defconfig" "ursa_user_defconfig")
BUILD_DATE=$(TZ=Asia/Jakarta date '+%d-%m-%Y')
BUILD_DATETIME=$(TZ=Asia/Jakarta date '+%d-%m-%Y %H:%M WIB')
GIT_SHA=$(git rev-parse HEAD)
GIT_SHORT_SHA=$(git rev-parse --short HEAD)
OUT_RELEASES_DIR="out/releases"

# Submodule versions
RESUKISU_COMMIT=$(cd drivers/kernelsu && git rev-parse --short HEAD 2>/dev/null || echo "unknown")
NOMOUNT_COMMIT=$(cd nomount && git rev-parse --short HEAD 2>/dev/null || echo "unknown")
BBG_COMMIT=$(cd Baseband-guard && git rev-parse --short HEAD 2>/dev/null || echo "unknown")

# SUSFS patch info (from source)
SUSFS_BASE="susfs_patch_to_4.9 (JackA1ltman variant)"

log() { echo -e "\033[1;32m[$(date '+%H:%M:%S')]\033[0m $*"; }
err() { echo -e "\033[1;31m[ERROR]\033[0m $*" >&2; }

clone_anykernel3() {
    local workdir="$1"
    if [[ ! -d "$workdir/AnyKernel3" ]]; then
        log "Cloning AnyKernel3 to $workdir"
        git clone --depth=1 https://github.com/osm0sis/AnyKernel3 "$workdir/AnyKernel3" 2>&1 | tail -3
    else
        log "AnyKernel3 already exists at $workdir/AnyKernel3"
    fi
}

detect_kernel_image() {
    local out_dir="$1"
    # Priority: Image.gz-dtb > Image.gz > Image
    for img in Image.gz-dtb Image.gz Image; do
        if [[ -f "$out_dir/arch/arm64/boot/$img" ]]; then
            echo "$img"
            return 0
        fi
    done
    return 1
}

detect_dtb_dtbo() {
    local out_dir="$1"
    local defconfig="$2"
    local has_dtbo=0
    local dtb_file=""

    # Check if BOARD_KERNEL_SEPARATED_DTBO is set in defconfig
    if grep -q "CONFIG_BUILD_ARM64_APPENDED_DTB_IMAGE=y" "arch/arm64/configs/$defconfig" 2>/dev/null; then
        # DTB is appended to Image, check for separate dtbo.img
        if [[ -f "$out_dir/arch/arm64/boot/dtbo.img" ]]; then
            has_dtbo=1
        fi
    fi

    # Find DTB file if not appended
    if [[ $has_dtbo -eq 0 ]]; then
        dtb_file=$(find "$out_dir/arch/arm64/boot/dts" -name "*.dtb" 2>/dev/null | head -1 || true)
    fi

    echo "$has_dtbo $dtb_file"
}

get_boot_partition() {
    local device="$1"
    # All target devices are non-A/B with standard boot partition path
    echo "/dev/block/bootdevice/by-name/boot"
}

generate_anykernel_sh() {
    local workdir="$1"
    local device="$2"
    local kernel_image="$3"
    local has_dtbo="$4"
    local dtb_file="$5"
    local block="$6"

    cat > "$workdir/AnyKernel3/anykernel.sh" <<EOF
# AnyKernel3 wrapper for $device
# Auto-generated by package_anykernel3.sh

properties() { '
kernel.string=ReSukiSU+SUSFS+Rekernel+NoMount+BBG for $device
do.devicecheck=1
do.modules=0
do.cleanup=1
do.cleanuponabort=0
device.name1=$device
device.name2=
device.name3=
device.name4=
device.name5=
supported.versions=
supported.patchlevels=
'; }

block=$block
is_slot_device=0
ramdisk_compression=auto

# Import functions from AnyKernel3 core
. /tmp/anykernel/anykernel-core.sh 2>/dev/null || true

# Boot image patching
flash_boot() {
    # Auto-detect and flash kernel image
    local kernel_img="$kernel_image"
    if [[ -f "\$KERNEL_IMG" ]]; then
        kernel_img="\$KERNEL_IMG"
    fi

    # Write kernel
    write_kernel "\$kernel_img"

    # Handle DTB/DTBO if needed
    if [[ $has_dtbo -eq 1 ]]; then
        # Device needs separate dtbo.img
        if [[ -f "\$DTBO_IMG" ]]; then
            flash_dtbo "\$DTBO_IMG"
        fi
    elif [[ -n "$dtb_file" ]]; then
        # DTB not appended, flash separately
        if [[ -f "\$DTB_IMG" ]]; then
            flash_dtbo "\$DTB_IMG"
        fi
    fi
}

# Device properties for recovery
device_properties() { '
ro.build.product=$device
ro.product.device=$device
'; }
EOF

    # Replace placeholders
    sed -i "s/has_dtbo=1/has_dtbo=$has_dtbo/" "$workdir/AnyKernel3/anykernel.sh"
    sed -i "s|dtb_file=\"\"|dtb_file=\"$dtb_file\"|" "$workdir/AnyKernel3/anykernel.sh"

    log "Generated anykernel.sh for $device (image: $kernel_image, dtbo: $has_dtbo, dtb: ${dtb_file:-none})"
}

prepare_anykernel_files() {
    local workdir="$1"
    local out_dir="$2"
    local kernel_image="$3"
    local has_dtbo="$4"
    local dtb_file="$5"

    # Copy kernel image
    cp "$out_dir/arch/arm64/boot/$kernel_image" "$workdir/AnyKernel3/Image" 2>/dev/null || true

    # Copy DTB if separate
    if [[ -n "$dtb_file" && -f "$dtb_file" ]]; then
        cp "$dtb_file" "$workdir/AnyKernel3/dtb.img"
        log "Copied DTB: $dtb_file -> dtb.img"
    fi

    # Copy DTBO if exists
    if [[ $has_dtbo -eq 1 && -f "$out_dir/arch/arm64/boot/dtbo.img" ]]; then
        cp "$out_dir/arch/arm64/boot/dtbo.img" "$workdir/AnyKernel3/dtbo.img"
        log "Copied DTBO: dtbo.img"
    fi
}

generate_changelog() {
    local device="$1"
    local workdir="$2"
    local zip_name="$3"

    cat > "$workdir/${zip_name%.zip}.md" <<EOF
Device : $device (Xiaomi Mi 8)
Tanggal build: $BUILD_DATETIME
Branch : feature/resukisu-susfs-rekernel-nomount-bbg
Commit : $GIT_SHA
Kernel base : $KERNEL_BASE

Fitur terintegrasi:
- ReSukiSU : $RESUKISU_COMMIT | CONFIG_KSU=y, CONFIG_KSU_SUSFS=y
- SUSFS : inline hook (JackA1ltman variant), base patch $SUSFS_BASE
- Rekernel : $GIT_SHORT_SHA (feature/resukisu-susfs-rekernel-nomount-bbg)
- NoMount : $NOMOUNT_COMMIT
- Baseband-guard (BBG): $BBG_COMMIT

Status build: SUCCESS
EOF

    log "Generated changelog: ${zip_name%.zip}.md"
}

create_zip() {
    local workdir="$1"
    local device="$2"
    local zip_name="$3"

    cd "$workdir/AnyKernel3"
    # Create zip excluding .git and any existing zips
    zip -r9 "../$zip_name" . -x "*.git*" -x "*.zip" -x "README*" 2>&1 | tail -5
    cd "$KERNEL_DIR"

    log "Created ZIP: $workdir/$zip_name"
}

package_device() {
    local device="$1"
    local defconfig="$2"
    local out_dir="out/$device"
    local workdir="$OUT_RELEASES_DIR/$device/${BUILD_DATE}_${GIT_SHORT_SHA}"
    local zip_name="${device}-${BRANCH_SHORT}-${BUILD_DATE}-${GIT_SHORT_SHA}.zip"

    log "=== Packaging $device ==="

    # Check build output exists
    if [[ ! -d "$out_dir" ]]; then
        err "Build output not found: $out_dir (run build first)"
        return 1
    fi

    # Detect kernel image
    kernel_image=$(detect_kernel_image "$out_dir") || {
        err "No kernel image found in $out_dir/arch/arm64/boot/"
        return 1
    }
    log "Detected kernel image: $kernel_image"

    # Detect DTB/DTBO
    read -r has_dtbo dtb_file <<< "$(detect_dtb_dtbo "$out_dir" "$defconfig")"
    log "DTB/DTBO detection: has_dtbo=$has_dtbo, dtb_file=${dtb_file:-none}"

    # Get boot partition
    block=$(get_boot_partition "$device")

    # Create work directory
    mkdir -p "$workdir"

    # Clone AnyKernel3
    clone_anykernel3 "$workdir"

    # Prepare files
    prepare_anykernel_files "$workdir" "$out_dir" "$kernel_image" "$has_dtbo" "$dtb_file"

    # Generate anykernel.sh
    generate_anykernel_sh "$workdir" "$device" "$kernel_image" "$has_dtbo" "$dtb_file" "$block"

    # Generate changelog
    generate_changelog "$device" "$workdir" "$zip_name"

    # Create ZIP
    create_zip "$workdir" "$device" "$zip_name"

    # Verify
    if [[ -f "$workdir/$zip_name" && -f "$workdir/${zip_name%.zip}.md" ]]; then
        log "SUCCESS: $device packaged to $workdir/"
        ls -lh "$workdir/"
    else
        err "FAILED: $device packaging incomplete"
        return 1
    fi
}

main() {
    # Parse CLI arguments for single-device mode (CI)
    local single_device=""
    local single_defconfig=""
    while [[ $# -gt 0 ]]; do
        case $1 in
            --device) single_device="$2"; shift 2 ;;
            --defconfig) single_defconfig="$2"; shift 2 ;;
            *) shift ;;
        esac
    done

    log "Starting AnyKernel3 packaging"
    log "Branch: $BRANCH_SHORT | Date: $BUILD_DATE | SHA: $GIT_SHORT_SHA"

    if [[ -n "$single_device" && -n "$single_defconfig" ]]; then
        # CI single-device mode
        package_device "$single_device" "$single_defconfig"
    else
        # Local multi-device mode
        for i in "${!DEVICES[@]}"; do
            device="${DEVICES[$i]}"
            defconfig="${DEFCONFIGS[$i]}"
            package_device "$device" "$defconfig" || err "Device $device failed, continuing..."
        done
    fi

    log "All devices processed. Release directory: $OUT_RELEASES_DIR"
    find "$OUT_RELEASES_DIR" -name "*.zip" -o -name "*.md" | sort
}

main "$@"