dtb-$(CONFIG_ARCH_QCOM)	+= apq8016-sbc.dtb msm8916-mtp.dtb
dtb-$(CONFIG_ARCH_QCOM)	+= msm8996-mtp.dtb
dtb-$(CONFIG_ARCH_QCOM)	+= apq8096-db820c.dtb

# Xiaomi SDM660 devices
dtb-$(CONFIG_ARCH_QCOM)	+= dipper-p0.dtb dipper-mp-v2.dtb dipper-mp-v2.1.dtb dipper-p0-v2.dtb dipper-p0-v2.1.dtb
dtb-$(CONFIG_ARCH_QCOM)	+= polaris-mp.dtb polaris-p0.dtb polaris-p1.dtb polaris-p2.dtb polaris-p3.dtb polaris-mp-v2.dtb polaris-mp-v2.1.dtb polaris-p0-v2.dtb polaris-p1-v2.dtb polaris-p1-v2.1.dtb polaris-p2-v2.dtb polaris-p2-v2.1.dtb polaris-p3-v2.dtb polaris-p3-v2.1.dtb
dtb-$(CONFIG_ARCH_QCOM)	+= beryllium-mp-v2.1.dtb beryllium-p0-v2.dtb beryllium-p0-v2.1.dtb beryllium-p1-v2.1.dtb beryllium-p2-v2.1.dtb
dtb-$(CONFIG_ARCH_QCOM)	+= equuleus-mp-v2.dtb equuleus-mp-v2.1.dtb equuleus-p0-v2.dtb equuleus-p0-v2.1.dtb equuleus-p1-v2.dtb equuleus-p1-v2.1.dtb
dtb-$(CONFIG_ARCH_QCOM)	+= perseus-mp-v2.1.dtb perseus-p0-v2.dtb perseus-p0-v2.1.dtb perseus-p1_2-v2.1.dtb perseus-p1-v2.1.dtb perseus-p2-v2.1.dtb perseus-p3-v2.1.dtb
dtb-$(CONFIG_ARCH_QCOM)	+= ursa-mp-v2.dtb ursa-mp-v2.1.dtb ursa-p0-v2.dtb ursa-p0-v2.1.dtb ursa-p1-v2.dtb ursa-p1-v2.1.dtb ursa-p2-v2.dtb ursa-p2-v2.1.dtb

always			:= $(dtb-y)
subdir-y		:= $(dts-dirs)
clean-files		:= *.dtb
